# Site settings
title: 
header-img: img/home-bg.png
email: emma.konrad92@gmail.com
copyright_name: emmakon
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: emmakonrad
github_username:  emmakon
learn_profile: emmakon
email_username: emma.konrad92@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
